version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JENKINS_IMAGE: "${JENKINS_IMAGE:-docker.io/jenkins/jenkins}"
        JENKINS_TAG: "${JENKINS_TAG:-lts}"          # see tags here: https://hub.docker.com/r/jenkins/jenkins/tags
        HOST_DOCKER_GID: "${HOST_DOCKER_GID:?err}"  # check *your* docker group id with: `getent group docker`
    environment: 
      - M2_CACHE_VOL=${M2_CACHE_VOL}
    ports:
    - "${JENKINS_PORT:-8080}:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "jenkins_home:/var/jenkins_home"
    networks:
      - ci_network
    restart: always
    
volumes:
  jenkins_home:
    name:
      jenkins_home
  m2_cache:
    name:
      ${M2_CACHE_VOL}
networks:
  ci_network:
    name: ci_network